/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


//stack memory calculations
#define SIZE_TASK_STACK             1024U  //1KB
#define SIZE_SCHEDULER_STACK        1024U  //1KB
#define SRAM_START                  0x20000000U
#define SIZE_SRAM                   ( (128) * (1024) )
#define SRAM_END                    ( (SRAM_START) + (SIZE_SRAM) )

//tasks stack init
#define T1_STACK_START              SRAM_END
#define T2_STACK_START              ( (SRAM_END) - (SIZE_TASK_STACK) )
#define T3_STACK_START              ( (SRAM_END) - (2 * SIZE_TASK_STACK) )
#define T4_STACK_START              ( (SRAM_END) - (3 * SIZE_TASK_STACK) )
#define SCHED_STACK_START           ( (SRAM_END) - (4 * SIZE_SCHEDULER_STACK) )

//mcu clk
#define TICK_HZ                     1000U  //1khz
#define HSI_CLOCK                   16000000U
#define SYSTICK_TIM_CLK             HSI_CLOCK
#define MAX_TASKS                   4

#define DUMMY_XPSR                  0x01000000U



void init_systick_timer(uint32_t tick_hz);
__attribute__ ((naked)) void init_scheduler_stack(uint32_t sche_top_of_stack);
void init_tasks_stacks(void);
void task1_handler(void); //user tasks
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void enable_processor_faults(void);
__attribute__ ((naked)) void switch_sp_to_psp(void);
uint32_t get_psp_value(void);
void save_psp_value(uint32_t current_psp_value);


uint32_t psp_of_tasks[MAX_TASKS]={T1_STACK_START,T2_STACK_START,T3_STACK_START,T4_STACK_START};
uint32_t task_handlers[MAX_TASKS];
uint8_t current_task = 0; //task 1 is running



int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	task_handlers[0] = (uint32_t)task1_handler;
	task_handlers[1] = (uint32_t)task2_handler;
	task_handlers[2] = (uint32_t)task3_handler;
	task_handlers[3] = (uint32_t)task4_handler;

	init_tasks_stacks();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

	for(;;);
}


void task1_handler(void)
{
	while(1)
	{
		printf("Task 1\n");
	}
}

void task2_handler(void)
{
	while(1)
	{
		printf("Task 2\n");
	}
}

void task3_handler(void)
{
	while(1)
	{
		printf("Task 3\n");
	}
}

void task4_handler(void)
{
	while(1)
	{
		printf("Task 4\n");
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
	uint32_t count_value = ( SYSTICK_TIM_CLK / tick_hz ) - 1;

	*pSRVR &= ~(0x00FFFFFF);
	*pSRVR |= count_value;

	*pSCSR |= (1<<1); //sys exe enabled
	*pSCSR |= (1<<2); //internal clock (processor clk)
	*pSCSR |= (1<<0); // enable counter
}

void save_psp_value(uint32_t current_psp_value)//current psp val
{
	psp_of_tasks[current_task] = current_psp_value;
}

void update_next_task()
{
	current_task++;
	current_task %= MAX_TASKS;
}



__attribute__ ((naked)) void SysTick_Handler(void)
{
	/*Saving the context of current task*/

	//Get current task PSP value
	__asm volatile("MRS R0,PSP");

	//Using PSP store SF2 remaining reg (R4 - R11)
	__asm volatile("STMDB R0!,{R4-R11}");


	__asm volatile("PUSH {LR}");
	//Saving current value of PSP
	__asm volatile("BL save_psp_value");


	/*Retrieving the context of next task*/

	//Decide next task to run
	__asm volatile("BL update_next_task");

	//get its PSP value
	__asm volatile("BL get_psp_value");

	//using this PSP retrieve SF2 of task
	__asm volatile("LDMIA R0!,{R4-R11}");

	//update PSP and exit
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}");

	__asm volatile("BX LR");
}

__attribute__ ((naked)) void init_scheduler_stack(uint32_t sche_top_of_stack)
{
	__asm volatile("MSR MSP,R0");
	__asm volatile("BX LR");
}

void init_tasks_stacks(void)
{
	uint32_t *pPSP;
	for(int i=0 ; i< MAX_TASKS ; i++)
	{
		pPSP = (uint32_t*)psp_of_tasks[i];

		pPSP--;
		*pPSP = DUMMY_XPSR; //0x01000000

		pPSP--;
		*pPSP = task_handlers[i]; //PC

		pPSP--;
		*pPSP = 0xFFFFFFFD; //LR

		for(int j=0 ;j<13 ;j++)
		{
			pPSP--;
			*pPSP = 0x00000000;
		}
		psp_of_tasks[i] = (uint32_t)pPSP;
	}

}

void enable_processor_faults(void)
{
	//enable configurable (faults) exceptions
	uint32_t *pSHCRS =(uint32_t*)0xE000ED24;
	*pSHCRS |= ( (1<<18) | (1<<17) | (1<<16) ); //16(memmanage) 17(bus fault) 18(usage fault)
}

void HardFault_Handler(void)
{
	while(1);
}
void MemManage_Handler(void)
{
	while(1);
}
void BusFault_Handler(void)
{
	while(1);
}

uint32_t get_psp_value(void)
{
	return psp_of_tasks[current_task];
}


__attribute__ ((naked)) void switch_sp_to_psp(void)
{
	//Init PSP with task1 stack start addr
	__asm volatile("PUSH {LR}");
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");

	//change SP to PSP using CONTROL REGISTER
	__asm volatile("MOV R0,0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");

}

